version: '2'

services:
  es-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "127.0.0.1:9200:9200"
    expose:
      - "9200"
      - "9300"
    environment:
      BM_ES_NODE_NAME: "es-master"
      ES_JAVA_OPTS: "-Xms250m -Xmx250m"
      BM_ES_MASTER: "true"
      BM_ES_DATA: "false"
      action.auto_create_index: "true"
      discovery.zen.ping.unicast.hosts: "es-master"
      discovery.zen.minimum_master_nodes: 1
      xpack.security.enabled: "false"
    networks:
      - net

  es-data:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    expose:
      - "9200"
      - "9300"
    environment:
      BM_ES_NODE_NAME: "es-data"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      BM_ES_MASTER: "false"
      BM_ES_DATA: "true"
      action.auto_create_index: "true"
      discovery.zen.ping.unicast.hosts: "es-master"
      discovery.zen.minimum_master_nodes: 1
      xpack.security.enabled: "false"
    networks:
      - net
    volumes:
      - es-data:/usr/share/elasticsearch/data
    depends_on:
      - es-master
    links:
      - es-master:es-master

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      xpack.security.enabled: "false"
    networks:
      - net
    depends_on:
      - es-master
    links:
      - es-master:elasticsearch

networks:
  net:
    driver: bridge

volumes:
  es-data: {}
